
import oru.inf.InfDB;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erik
 */
public class AdminUtrustning extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form AdminUtrustning
     */
    public AdminUtrustning(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistreraUtrustning = new javax.swing.JButton();
        btnTaBortUtrustning = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        btnLanaUtrustning = new javax.swing.JButton();
        btnMinUtrustning = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRubrik.setForeground(new java.awt.Color(51, 51, 51));
        lblRubrik.setText("Utrustning");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MiBlogga3.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        btnRegistreraUtrustning.setBackground(new java.awt.Color(51, 51, 51));
        btnRegistreraUtrustning.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistreraUtrustning.setText("Registrera utrustning");
        btnRegistreraUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraUtrustningActionPerformed(evt);
            }
        });

        btnTaBortUtrustning.setBackground(new java.awt.Color(51, 51, 51));
        btnTaBortUtrustning.setForeground(new java.awt.Color(255, 255, 255));
        btnTaBortUtrustning.setText("Ta bort utrustning");
        btnTaBortUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortUtrustningActionPerformed(evt);
            }
        });

        btnTillbaka.setBackground(new java.awt.Color(51, 51, 51));
        btnTillbaka.setForeground(new java.awt.Color(255, 255, 255));
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnLanaUtrustning.setBackground(new java.awt.Color(51, 51, 51));
        btnLanaUtrustning.setForeground(new java.awt.Color(255, 255, 255));
        btnLanaUtrustning.setText("Låna utrustning");
        btnLanaUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanaUtrustningActionPerformed(evt);
            }
        });

        btnMinUtrustning.setBackground(new java.awt.Color(51, 51, 51));
        btnMinUtrustning.setForeground(new java.awt.Color(255, 255, 255));
        btnMinUtrustning.setText("Min utrustning");
        btnMinUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinUtrustningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnTillbaka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistreraUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLanaUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTaBortUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(btnMinUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTillbaka)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistreraUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaBortUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLanaUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Förnyar sidan efter man tryckt på registrera knappen
    private void btnRegistreraUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraUtrustningActionPerformed
        dispose();
        new RegistreraUtrustning(idb).setVisible(true);
    }//GEN-LAST:event_btnRegistreraUtrustningActionPerformed

    // Förnyar sidan efter man tryckt på ta bort knappen
    private void btnTaBortUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortUtrustningActionPerformed
        dispose();
        new AdminTaBortUtrustning(idb).setVisible(true);
    }//GEN-LAST:event_btnTaBortUtrustningActionPerformed

    //avslutar en pågående sida och öppnar en föregående
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        dispose();
        new InloggadAdmin(idb).setVisible(true);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnLanaUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanaUtrustningActionPerformed
        dispose();
        new LanaUtrustning(idb).setVisible(true);
    }//GEN-LAST:event_btnLanaUtrustningActionPerformed

    private void btnMinUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinUtrustningActionPerformed
        dispose();
        new MinUtrustning(idb, true).setVisible(true);
    }//GEN-LAST:event_btnMinUtrustningActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLanaUtrustning;
    private javax.swing.JButton btnMinUtrustning;
    private javax.swing.JButton btnRegistreraUtrustning;
    private javax.swing.JButton btnTaBortUtrustning;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblRubrik;
    // End of variables declaration//GEN-END:variables
}
