/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author scott
 */
public class AlienLoggaIn extends javax.swing.JFrame {

    /**
     * Creates new form AlienLoggaIn
     */
    public AlienLoggaIn(InfDB idb) {
        initComponents();
        this.idb = idb;
       

    }
    
    // kollar så lösen och användarnman matchar
    private void getInloggsuppgifter(){
             try {
            if(idb.fetchSingle(anvandarNamnLosenord) == null){
             JOptionPane.showMessageDialog(rootPane, "Fel användarnamn eller lösenord");
            } else 
            {
                idb.fetchSingle(anvandarNamnLosenord);
                dispose();
                new InloggadAlien(idb).setVisible(true);
            }

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(rootPane, "Användarnamn eller lösenord är fel.");
            System.out.print(ex);
        }
    }
    
    // antal getmeetoder som används för InloggadAlien
    public static String getAnsvarigAgent(){
        return ansvarigAgent;
    }
    public static String getOmradesChef(){
        return omradesChef;
    }
    public static String getOmradesChefTelefon(){
        return omradesChefTelefon;
    }
    public static String getOmrade(){
        return omrade;
    }
    public static String getAlien(){
        return alienID;
    }
    
    // settar varibler om alien i fråga.
    private void setVariables(){
        try{
       anvandarNamnLosenord = "SELECT Alien_ID FROM Alien WHERE losenord = '" + String.valueOf(pswLosenord.getPassword()) + "' AND Namn= '" + txtNamn.getText() + "';";
       alienID = idb.fetchSingle(anvandarNamnLosenord);
       ansvarigAgent = idb.fetchSingle("SELECT Ansvarig_Agent FROM Alien WHERE Alien_ID =" + idb.fetchSingle(anvandarNamnLosenord) +";");
       String agentID = idb.fetchSingle("SELECT Agent_ID FROM Omradeschef WHERE Omrade =" + idb.fetchSingle("SELECT Finns_I FROM Plats WHERE Plats_ID = " + idb.fetchSingle("SELECT Plats FROM Alien WHERE Alien_ID =" + alienID +";") +";")+";");
       omradesChef = idb.fetchSingle("SELECT Namn from Agent WHERE agent_ID = " + agentID + ";");
       omradesChefTelefon = idb.fetchSingle("SELECT Telefon FROM Agent WHERE Agent_ID =" + agentID + ";");
       omrade = idb.fetchSingle("SELECT plats FROM Alien WHERE Alien_ID =" + alienID);
       System.out.println(omradesChef);
        } catch (InfException ex) {
            System.out.println(ex);
            System.out.println(omradesChef);
        }
    }
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNamn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLoggaIn = new javax.swing.JButton();
        pswLosenord = new javax.swing.JPasswordField();
        btnTillbaka = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Men in Black Skandinavien");

        txtNamn.setColumns(7);
        txtNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Namn");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Lösenord:");

        btnLoggaIn.setBackground(new java.awt.Color(51, 51, 51));
        btnLoggaIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLoggaIn.setText("Logga in");
        btnLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaInActionPerformed(evt);
            }
        });

        pswLosenord.setColumns(7);

        btnTillbaka.setBackground(new java.awt.Color(51, 51, 51));
        btnTillbaka.setForeground(new java.awt.Color(255, 255, 255));
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MiBlogga2.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Alien LOGIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pswLosenord, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(btnLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnTillbaka)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(229, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(125, 125, 125)))
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTillbaka)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4))
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // loggar in i systemet
    private void btnLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaInActionPerformed
        // TODO add your handling code here:
        if (Validering.textFaltHarVarde(txtNamn) && Validering.textFaltHarVarde(pswLosenord)) {
            setVariables();
            getInloggsuppgifter();
        }
    }//GEN-LAST:event_btnLoggaInActionPerformed

    //avslutar en pågående sida och öppnar en föregående
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        dispose();
        new FörstaFönster(idb).setVisible(true);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void txtNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamnActionPerformed

    /**
     * @param args the command line arguments
     */
  
    
    private InfDB idb;
    private static String alienID;
    private static String omrade;
    private static String omradesChefTelefon;
    private static String omradesChef;
    private static String ansvarigAgent;
    private static String anvandarNamnLosenord;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pswLosenord;
    private javax.swing.JTextField txtNamn;
    // End of variables declaration//GEN-END:variables
}
