/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfException;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;
import oru.inf.InfDB;



/**
 *
 * @author scott
 */
public class InloggadAlien extends javax.swing.JFrame {

    /**
     * Creates new form AlienInloggad
     */
    public InloggadAlien(InfDB idb) {
        this.idb = idb;
        initComponents();
        ansvarigAgent = AlienLoggaIn.getAnsvarigAgent();
        omradesChef = AlienLoggaIn.getOmradesChef();
        omradesChefTelefon = AlienLoggaIn.getOmradesChefTelefon();
        setAnsvarigAgentLabel();
        setOmradesChef();
        fyllTextArea();
        fyllcbPlats();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pswGammaltLosen = new javax.swing.JPasswordField();
        lblLosenord = new javax.swing.JLabel();
        lblNyttLosen = new javax.swing.JLabel();
        pswNyttLosen = new javax.swing.JPasswordField();
        lblBekrafta = new javax.swing.JLabel();
        pswBekraftaLosen = new javax.swing.JPasswordField();
        btnBytLosenord = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        lblStaticAgent = new javax.swing.JLabel();
        lblStaticTelefon = new javax.swing.JLabel();
        lblAgent = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblOmradesChefNamn = new javax.swing.JLabel();
        lblOmradesChefTelefon = new javax.swing.JLabel();
        scrollArea = new javax.swing.JScrollPane();
        txtareaInfo = new javax.swing.JTextArea();
        btnListaAliens = new javax.swing.JButton();
        btnMaila = new javax.swing.JButton();
        cbPlats = new javax.swing.JComboBox<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Men in Black Skandinavien");
        setBackground(new java.awt.Color(51, 51, 51));

        pswGammaltLosen.setColumns(6);

        lblLosenord.setText("Lösenord:");

        lblNyttLosen.setText("Nytt lösenord:");

        pswNyttLosen.setColumns(6);
        pswNyttLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswNyttLosenActionPerformed(evt);
            }
        });

        lblBekrafta.setText("Bekräfta lösenord:");

        pswBekraftaLosen.setColumns(6);

        btnBytLosenord.setBackground(new java.awt.Color(51, 51, 51));
        btnBytLosenord.setForeground(new java.awt.Color(255, 255, 255));
        btnBytLosenord.setText("Byt lösenord");
        btnBytLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBytLosenordActionPerformed(evt);
            }
        });

        btnTillbaka.setBackground(new java.awt.Color(51, 51, 51));
        btnTillbaka.setForeground(new java.awt.Color(255, 255, 255));
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        lblStaticAgent.setText("Ansvarig agent:");

        lblStaticTelefon.setText("Telefonnummer:");

        lblAgent.setText("HämtadAgent");

        lblTelefon.setText("hämtadTelefon");

        lblOmradesChefNamn.setText("områdeschefAgent");

        lblOmradesChefTelefon.setText("områdeschefNummer");

        txtareaInfo.setEditable(false);
        txtareaInfo.setBackground(new java.awt.Color(51, 51, 51));
        txtareaInfo.setColumns(2);
        txtareaInfo.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtareaInfo.setForeground(new java.awt.Color(255, 255, 255));
        txtareaInfo.setLineWrap(true);
        txtareaInfo.setRows(5);
        txtareaInfo.setAutoscrolls(false);
        scrollArea.setViewportView(txtareaInfo);

        btnListaAliens.setBackground(new java.awt.Color(51, 51, 51));
        btnListaAliens.setForeground(new java.awt.Color(255, 255, 255));
        btnListaAliens.setText("Lista aliens i område:");
        btnListaAliens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaAliensActionPerformed(evt);
            }
        });

        btnMaila.setBackground(new java.awt.Color(51, 51, 51));
        btnMaila.setForeground(new java.awt.Color(255, 255, 255));
        btnMaila.setText("Maila områdeschef");
        btnMaila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMailaActionPerformed(evt);
            }
        });

        cbPlats.setBackground(new java.awt.Color(51, 51, 51));
        cbPlats.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBekrafta)
                    .addComponent(pswBekraftaLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBytLosenord)
                    .addComponent(lblLosenord))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMaila)
                            .addComponent(lblOmradesChefTelefon)
                            .addComponent(lblOmradesChefNamn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollArea, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnListaAliens)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStaticTelefon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTelefon))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStaticAgent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAgent)))
                        .addContainerGap(410, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTillbaka)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pswNyttLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNyttLosen)
                            .addComponent(pswGammaltLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTillbaka)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStaticAgent)
                    .addComponent(lblAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStaticTelefon)
                    .addComponent(lblLosenord)
                    .addComponent(lblTelefon))
                .addGap(4, 4, 4)
                .addComponent(pswGammaltLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNyttLosen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswNyttLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOmradesChefNamn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOmradesChefTelefon)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBekrafta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pswBekraftaLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMaila)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnListaAliens)
                        .addComponent(cbPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBytLosenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollArea, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pswNyttLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswNyttLosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswNyttLosenActionPerformed

    // denna byter lösen, samt kollar så lösenordet är gilltigt med hjälp av valideringsklass.
    private void btnBytLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBytLosenordActionPerformed
        setlosenord();
        if (Validering.textFaltHarVarde(pswGammaltLosen) && Validering.textFaltHarVarde(pswNyttLosen) && Validering.textFaltHarVarde(pswBekraftaLosen)) {
            try {
                if (idb.fetchSingle("SELECT Losenord FROM Alien WHERE Alien_ID =" + AlienLoggaIn.getAlien()).equals(gammaltLosen)) {
                    if (nyttLosen.equals(bekraftaLosen)) {
                        if (Validering.isPasswordValid(pswNyttLosen) && Validering.isPasswordValid(pswBekraftaLosen)) {
                            idb.update("UPDATE Alien SET Losenord = '" + nyttLosen + "' WHERE Alien_ID =" + AlienLoggaIn.getAlien() + ";");
                            JOptionPane.showMessageDialog(rootPane, "Lösenord upddaterat.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Nya lösenord matchar inte");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Fel lösenord");
                }
            } catch (InfException ex) {

            }
        }
    }//GEN-LAST:event_btnBytLosenordActionPerformed

    //avslutar en pågående sida och öppnar en föregående
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        dispose();
        new AlienLoggaIn(idb).setVisible(true);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    // listar alla aliens i ett valt område.
    private void btnListaAliensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaAliensActionPerformed
        try {
            String valjPlats = idb.fetchSingle("SELECT Plats_ID FROM Plats WHERE Benamning ='" + cbPlats.getItemAt(cbPlats.getSelectedIndex()) + "';");
            String fraga = "SELECT Namn, Telefon FROM Alien WHERE Plats ='" + valjPlats + "';";

            ArrayList<HashMap<String, String>> info = idb.fetchRows(fraga);
            txtareaInfo.setText("Namn:" + " ".repeat(16) + "Telefon: \n");
            for (int i = 0; i < info.size(); i++) {
                HashMap<String, String> hashmap = info.get(i);

                System.out.println(hashmap.get("Namn") + " Telefon: " + hashmap.get("Telefon") + "\n");
                txtareaInfo.append((hashmap.get("Namn") + " ".repeat(20)).substring(0, 21) + hashmap.get("Telefon") + "\n");
                txtareaInfo.setCaretPosition(0);
            }
        } catch (InfException ex) {
            Logger.getLogger(InloggadAlien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListaAliensActionPerformed

   
    // fyller comboboxen för plats
    private void fyllcbPlats() {
        String fraga = "SELECT benamning AS Område FROM plats";

        ArrayList<String> allaPlatser;

        try {
            allaPlatser = idb.fetchColumn(fraga);
            for (String namn : allaPlatser) {
                cbPlats.addItem(namn);
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, "Fel har uppstått.");
        }
    }

    // fyller text arean med text efter valt område
    private void fyllTextArea() {
        String fraga = "SELECT Namn, Telefon FROM Alien WHERE Plats =" + AlienLoggaIn.getOmrade();

        try {
            ArrayList<HashMap<String, String>> info = idb.fetchRows(fraga);
            txtareaInfo.setText("Namn:" + " ".repeat(16) + "Telefon: \n");
            for (int i = 0; i < info.size(); i++) {
                HashMap<String, String> hashmap = info.get(i);

                System.out.println(hashmap.get("Namn") + " Telefon: " + hashmap.get("Telefon") + "\n");
                txtareaInfo.append((hashmap.get("Namn") + " ".repeat(20)).substring(0, 21) + hashmap.get("Telefon") + "\n");
                txtareaInfo.setCaretPosition(0);
            }

        } catch (InfException ex) {
            Logger.getLogger(InloggadAlien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // kallar på metoden mail för att öppna applikationen
    // OBS! FUNGERAR ENDAST PÅ PC (EJ MAC)
    private void btnMailaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMailaActionPerformed
        try {
            // TODO add your handling code here:
            mail();
        } catch (URISyntaxException ex) {
            Logger.getLogger(InloggadAlien.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Tyvärr stöds ej denna funktion på din dator.");
        }
    }//GEN-LAST:event_btnMailaActionPerformed

    // tar dig till din mail applikation vid behov av hjälp.
    private void mail() throws URISyntaxException {
        Desktop desktop;
        if (Desktop.isDesktopSupported() && (desktop = Desktop.getDesktop()).isSupported(Desktop.Action.MAIL)) {
            URI mailto = new URI(getMail());
            try {
                desktop.mail(mailto);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, "Tyvärr stöds ej denna funktion på din dator.");
                Logger.getLogger(InloggadAlien.class.getName()).log(Level.SEVERE, null, ex);
               
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tyvärr stöds ej denna funktion på din dator.");
           //throw new RuntimeException("Tyvärr stöds ej denna funktion på din dator."); 
        }
    }

    private String getMail() {
        String mail = "mailto:" + omradesChefTelefon + "@mibskandinavien.se?subject=Hjälp!";
        return mail;
    }


    // visar ansvarig agent för den inloggade alien
    private void setAnsvarigAgentLabel() {
        try {
            lblAgent.setText(idb.fetchSingle("SELECT Namn FROM Agent WHERE Agent_ID = " + ansvarigAgent + ";"));
            lblTelefon.setText(idb.fetchSingle("SELECT Telefon FROM Agent WHERE Agent_ID = " + ansvarigAgent + ";"));
        } catch (InfException ex) {
            System.out.println(ex);
            System.out.println(ansvarigAgent);
        }
    }

    // visar nuvarande området för den inloggade alien
    private void setOmradesChef() {
        lblOmradesChefNamn.setText("Områdeschef: " + omradesChef);
        lblOmradesChefTelefon.setText("Telefonnummer: " + omradesChefTelefon);
    }

  
    private void setlosenord() {
        gammaltLosen = String.valueOf(pswGammaltLosen.getPassword());
        nyttLosen = String.valueOf(pswNyttLosen.getPassword());
        bekraftaLosen = String.valueOf(pswBekraftaLosen.getPassword());
    }


    /**
     * @param args the command line arguments
     */
   

    private InfDB idb;
    private String gammaltLosen;
    private String nyttLosen;
    private String bekraftaLosen;
    private static String omradesChefTelefon;
    private static String omradesChef;
    private static String ansvarigAgent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBytLosenord;
    private javax.swing.JButton btnListaAliens;
    private javax.swing.JButton btnMaila;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbPlats;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAgent;
    private javax.swing.JLabel lblBekrafta;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblNyttLosen;
    private javax.swing.JLabel lblOmradesChefNamn;
    private javax.swing.JLabel lblOmradesChefTelefon;
    private javax.swing.JLabel lblStaticAgent;
    private javax.swing.JLabel lblStaticTelefon;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JPasswordField pswBekraftaLosen;
    private javax.swing.JPasswordField pswGammaltLosen;
    private javax.swing.JPasswordField pswNyttLosen;
    private javax.swing.JScrollPane scrollArea;
    private javax.swing.JTextArea txtareaInfo;
    // End of variables declaration//GEN-END:variables
}
