
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Erik
 */
public class RegistreraAlien extends javax.swing.JFrame {

    private InfDB idb;
    private boolean admin;

    /**
     * Creates new form AdminRegistreraAlien
     */
    public RegistreraAlien(InfDB idb) {
        initComponents();
        this.idb = idb;
        fylliCbPlats();
        fylliAlienID();
        fylliDatum();
        fyllicbAgent();
        fyllcbRas();
        admin = false;
    }

    public RegistreraAlien(InfDB idb, boolean b) {
        initComponents();
        this.idb = idb;
        fylliCbPlats();
        fylliAlienID();
        fylliDatum();
        fyllicbAgent();
        fyllcbRas();
        admin = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFaltLosen = new javax.swing.JPasswordField();
        lblDatum = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        lblShowDatum = new javax.swing.JLabel();
        lblRubrik = new javax.swing.JLabel();
        lvlLosenord = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        txtFaltNamn = new javax.swing.JTextField();
        lblTelefon = new javax.swing.JLabel();
        txtFaltTelefon = new javax.swing.JTextField();
        cbPlats = new javax.swing.JComboBox<>();
        lblAgent = new javax.swing.JLabel();
        lblPlats = new javax.swing.JLabel();
        cbAgent = new javax.swing.JComboBox<>();
        lblAlien_ID = new javax.swing.JLabel();
        btnRegistrera = new javax.swing.JButton();
        lblAlien = new javax.swing.JLabel();
        lblRas = new javax.swing.JLabel();
        cbRas = new javax.swing.JComboBox<>();
        txtFaltExtra = new javax.swing.JTextField();
        lblExtra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFaltLosen.setColumns(6);

        lblDatum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDatum.setText("Datum:");

        btnTillbaka.setBackground(new java.awt.Color(51, 51, 51));
        btnTillbaka.setForeground(new java.awt.Color(255, 255, 255));
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        lblRubrik.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRubrik.setForeground(new java.awt.Color(51, 51, 51));
        lblRubrik.setText("Registrera Alien");

        lvlLosenord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lvlLosenord.setText("Lösenord:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MiBlogga3.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        lblNamn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNamn.setText("Namn:");

        txtFaltNamn.setColumns(6);
        txtFaltNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaltNamnActionPerformed(evt);
            }
        });

        lblTelefon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefon.setText("Telefon:");

        txtFaltTelefon.setColumns(7);
        txtFaltTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaltTelefonActionPerformed(evt);
            }
        });

        cbPlats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlatsActionPerformed(evt);
            }
        });

        lblAgent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAgent.setText("Ansvarig Agent:");

        lblPlats.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPlats.setText("Område:");

        cbAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgentActionPerformed(evt);
            }
        });

        lblAlien_ID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAlien_ID.setText("Alien_ID");

        btnRegistrera.setBackground(new java.awt.Color(51, 51, 51));
        btnRegistrera.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrera.setText("Registrera");
        btnRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraActionPerformed(evt);
            }
        });

        lblRas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRas.setText("Ras:");

        cbRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRasActionPerformed(evt);
            }
        });

        txtFaltExtra.setColumns(5);
        txtFaltExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaltExtraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(btnRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTillbaka)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(125, 125, 125)
                                                .addComponent(cbRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lvlLosenord)
                                                    .addComponent(lblNamn)
                                                    .addComponent(lblDatum)
                                                    .addComponent(lblAlien_ID))
                                                .addGap(57, 57, 57)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtFaltNamn)
                                                    .addComponent(lblShowDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtFaltLosen)
                                                    .addComponent(lblAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblTelefon)
                                                    .addComponent(lblAgent)
                                                    .addComponent(lblPlats))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(16, 16, 16)
                                                        .addComponent(txtFaltTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(cbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cbPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFaltExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblRas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTillbaka)
                        .addGap(46, 46, 46)
                        .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlien_ID)
                            .addComponent(lblAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatum)
                            .addComponent(lblShowDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFaltNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNamn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lvlLosenord)
                            .addComponent(txtFaltLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefon)
                            .addComponent(txtFaltTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAgent)
                            .addComponent(cbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlats)
                            .addComponent(cbPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRas)
                    .addComponent(cbRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFaltExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        dispose();
        if (admin) {
            new InloggadAdmin(idb).setVisible(true);
        } else {
            new InloggadAgent(idb).setVisible(true);
        }

    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void txtFaltTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaltTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaltTelefonActionPerformed

    private void cbPlatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPlatsActionPerformed

    private void cbAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAgentActionPerformed

    // när knappen trycks så uppdateras databasen med vad som finns i fälten
    private void btnRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraActionPerformed
        try {
            String ras = cbRas.getItemAt(cbRas.getSelectedIndex());
            String rasFraga = "";
            //Validera!!
            if (ras.equals("Boglodite") || ras.equals("Squid")) {
                rasFraga = "INSERT INTO " + ras + " VALUES (" + lblAlien.getText() + ", " + txtFaltExtra.getText() + ");";
            } else if (ras.equals("Worm")) {
                rasFraga = "INSERT INTO " + ras + " VALUES ('" + lblAlien.getText() + "');";
            }

            String valtLosen = String.valueOf(txtFaltLosen.getPassword());
            String valtNamn = txtFaltNamn.getText();
            String valtTelefon = txtFaltTelefon.getText();
            String valdAgent = idb.fetchSingle("SELECT Agent_ID FROM agent WHERE namn= '" + cbAgent.getItemAt(cbAgent.getSelectedIndex()) + "'");
            String valdPlats = idb.fetchSingle("SELECT plats_ID FROM Plats WHERE benamning= '" + cbPlats.getItemAt(cbPlats.getSelectedIndex()) + "'");
            String fraga = ("INSERT INTO Alien VALUES (" + fylliAlienID() + ", " + "curdate()" + ", '" + valtLosen + "', '" + valtNamn + "', " + valtTelefon + ", " + valdPlats + ", " + valdAgent + ");");
            
            if (Validering.isPasswordValid(txtFaltLosen) && Validering.textFaltHarVarde(txtFaltNamn) && Validering.isHeltal(txtFaltTelefon)) {
                if (txtFaltExtra.isVisible() && Validering.textFaltHarVarde(txtFaltExtra) && Validering.isHeltal(txtFaltExtra)) {
                    idb.insert(fraga);
                    idb.insert(rasFraga);
                    JOptionPane.showMessageDialog(null, valtNamn + " har registrerats");
                    dispose();
                    if (admin) {
                        new RegistreraAlien(idb, true).setVisible(true);
                    } else {
                        new RegistreraAlien(idb).setVisible(true);
                    }
                } else if (!txtFaltExtra.isVisible()) {
                    idb.insert(fraga);
                    idb.insert(rasFraga);
                    JOptionPane.showMessageDialog(null, valtNamn + " har registrerats");
                    dispose();
                    if (admin) {
                        new RegistreraAlien(idb, true).setVisible(true);
                    } else {
                        new RegistreraAlien(idb).setVisible(true);
                    }
                }
            }
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        } catch (Exception ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        }

    }//GEN-LAST:event_btnRegistreraActionPerformed

    // beroende på vilken ras som är vald så kan det komma upp ett textfält för att ange ex. antal armar.
    private void cbRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRasActionPerformed
        String ras = cbRas.getItemAt(cbRas.getSelectedIndex());
        if (ras.equals("Boglodite")) {
            lblExtra.setVisible(true);
            lblExtra.setText("Antal Boogies");
            txtFaltExtra.setVisible(true);
        }
        if (ras.equals("Squid")) {
            lblExtra.setVisible(true);
            lblExtra.setText("Antal Armar");
            txtFaltExtra.setVisible(true);
        }
        if (ras.equals("Worm")) {
            lblExtra.setVisible(false);
            txtFaltExtra.setVisible(false);
        }
        if (ras.equals("Okänd ras")) {
            lblExtra.setVisible(false);
            txtFaltExtra.setVisible(false);
        }
    }//GEN-LAST:event_cbRasActionPerformed

    private void txtFaltNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaltNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaltNamnActionPerformed

    private void txtFaltExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaltExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaltExtraActionPerformed
    
    // fyller i comboboxen för agent
    public void fyllicbAgent() {
        try {
            String fraga = "SELECT Namn from agent;";
            ArrayList<String> allaNamn;
            allaNamn = idb.fetchColumn(fraga);

            for (String namn : allaNamn) {
                cbAgent.addItem(namn);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        } catch (Exception ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());

        }
    }

    

    // den ger oss ett id som är unikt
    public String fylliAlienID() {
        String stringAlienID = "";
        try {
            String fraga = idb.fetchSingle("SELECT max(Alien_ID) FROM alien;");
            int alienID = Integer.parseInt(fraga) + 1;
            stringAlienID = Integer.toString(alienID);
            lblAlien.setText(stringAlienID);
        
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        } catch (Exception ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        }

        return stringAlienID;
    }

    // den visar dagens datum, automatiskt.
    public String fylliDatum() {
        String datum = "";
        try {
            String fraga = "SELECT CURDATE();";
            datum = idb.fetchSingle(fraga);
            lblShowDatum.setText(datum);
            System.out.println(datum);
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        } catch (Exception ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        }
        return datum;
    }

    // fyller i comboboxen för plats.
    public void fylliCbPlats() {
        String fraga = "SELECT benamning from plats";

        ArrayList<String> allaOmraden;

        try {

            allaOmraden = idb.fetchColumn(fraga);

            for (String namn : allaOmraden) {
                cbPlats.addItem(namn);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        } catch (Exception ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        }
    }

    // fyller i comboboxen för ras.
    public void fyllcbRas() {
        cbRas.addItem("Boglodite");
        cbRas.addItem("Squid");
        cbRas.addItem("Worm");
        cbRas.addItem("Okänd ras");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrera;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbAgent;
    private javax.swing.JComboBox<String> cbPlats;
    private javax.swing.JComboBox<String> cbRas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAgent;
    private javax.swing.JLabel lblAlien;
    private javax.swing.JLabel lblAlien_ID;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblExtra;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblPlats;
    private javax.swing.JLabel lblRas;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblShowDatum;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lvlLosenord;
    private javax.swing.JTextField txtFaltExtra;
    private javax.swing.JPasswordField txtFaltLosen;
    private javax.swing.JTextField txtFaltNamn;
    private javax.swing.JTextField txtFaltTelefon;
    // End of variables declaration//GEN-END:variables
}
