
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

public class SokAlien extends javax.swing.JFrame {

    private InfDB idb;
    private boolean admin;

    /**
     * Creates new form SokAlien
     */
    public SokAlien(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllicbPlats();
        fyllicbRas();
        admin = false;
    }

    public SokAlien(InfDB idb, boolean b) {
        initComponents();
        this.idb = idb;
        fyllicbPlats();
        fyllicbRas();
        admin = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSokNamn = new javax.swing.JButton();
        txtFaltNamn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnTillbaka = new javax.swing.JButton();
        cbPlats = new javax.swing.JComboBox<>();
        btnSokOmrade = new javax.swing.JButton();
        lblSokNamn = new javax.swing.JLabel();
        lblSokOmrade = new javax.swing.JLabel();
        btbSokDatum = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFaltFranDatum = new javax.swing.JTextField();
        txtFaltTillDatum = new javax.swing.JTextField();
        lblFranDatum = new javax.swing.JLabel();
        lblTillDatum = new javax.swing.JLabel();
        lblSokRas = new javax.swing.JLabel();
        cbRas = new javax.swing.JComboBox<>();
        btnSokRas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Alien-Databas");

        btnSokNamn.setBackground(new java.awt.Color(51, 51, 51));
        btnSokNamn.setForeground(new java.awt.Color(255, 255, 255));
        btnSokNamn.setText("Sök");
        btnSokNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokNamnActionPerformed(evt);
            }
        });

        txtFaltNamn.setColumns(7);
        txtFaltNamn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFaltNamnFocusGained(evt);
            }
        });
        txtFaltNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaltNamnActionPerformed(evt);
            }
        });

        txtArea.setBackground(new java.awt.Color(51, 51, 51));
        txtArea.setColumns(20);
        txtArea.setForeground(new java.awt.Color(255, 255, 255));
        txtArea.setRows(5);
        txtArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(txtArea);

        btnTillbaka.setBackground(new java.awt.Color(51, 51, 51));
        btnTillbaka.setForeground(new java.awt.Color(255, 255, 255));
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        cbPlats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlatsActionPerformed(evt);
            }
        });

        btnSokOmrade.setBackground(new java.awt.Color(51, 51, 51));
        btnSokOmrade.setForeground(new java.awt.Color(255, 255, 255));
        btnSokOmrade.setText("Sök");
        btnSokOmrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokOmradeActionPerformed(evt);
            }
        });

        lblSokNamn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSokNamn.setForeground(new java.awt.Color(51, 51, 51));
        lblSokNamn.setText("Sök namn");

        lblSokOmrade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSokOmrade.setForeground(new java.awt.Color(51, 51, 51));
        lblSokOmrade.setText("Sök område");

        btbSokDatum.setBackground(new java.awt.Color(51, 51, 51));
        btbSokDatum.setForeground(new java.awt.Color(255, 255, 255));
        btbSokDatum.setText("Sök");
        btbSokDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbSokDatumActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(60, 63, 54));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Sök registreringsdatum");

        txtFaltFranDatum.setColumns(8);
        txtFaltFranDatum.setText("yyyy-mm-dd");

        txtFaltTillDatum.setColumns(8);
        txtFaltTillDatum.setText("yyyy-mm-dd");
        txtFaltTillDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaltTillDatumActionPerformed(evt);
            }
        });

        lblFranDatum.setBackground(new java.awt.Color(51, 51, 51));
        lblFranDatum.setText("Från datum:");

        lblTillDatum.setBackground(new java.awt.Color(51, 51, 51));
        lblTillDatum.setText("Till datum:");

        lblSokRas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSokRas.setForeground(new java.awt.Color(51, 51, 51));
        lblSokRas.setText("Sök alien-ras");

        cbRas.setToolTipText("");
        cbRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRasActionPerformed(evt);
            }
        });

        btnSokRas.setBackground(new java.awt.Color(51, 51, 51));
        btnSokRas.setForeground(new java.awt.Color(255, 255, 255));
        btnSokRas.setText("Sök");
        btnSokRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokRasActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MiBlogga3.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSokNamn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFaltNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSokNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSokRas)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSokOmrade)
                                    .addComponent(cbPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSokRas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSokOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFranDatum)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFaltFranDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTillDatum)
                                            .addComponent(txtFaltTillDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btbSokDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTillbaka)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblSokRas, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btnTillbaka)
                                .addGap(90, 90, 90)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSokNamn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSokRas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblSokOmrade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSokOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtFaltFranDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFranDatum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTillDatum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFaltTillDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btbSokDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFaltNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSokNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtFaltNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaltNamnActionPerformed
        txtFaltNamn.setText("");
    }//GEN-LAST:event_txtFaltNamnActionPerformed

    // tar fram allt från en Alien i alientabellen vid sökning av en giltig Alien
    private void btnSokNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokNamnActionPerformed
        txtArea.setText("");
        String namn = txtFaltNamn.getText();
        String fraga = "SELECT * FROM alien WHERE namn ='" + namn + "';";
        System.out.print(fraga);
        sokAllAliendata(fraga);


    }//GEN-LAST:event_btnSokNamnActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        dispose();
        if (admin) {
            new InloggadAdmin(idb).setVisible(true);
        } else {
            new InloggadAgent(idb).setVisible(true);
        }

    }//GEN-LAST:event_btnTillbakaActionPerformed

    // tar fram allt i Alientabellen vid sökning på ett specifikt område.
    private void btnSokOmradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokOmradeActionPerformed
        txtArea.setText("");
        String benamning = cbPlats.getItemAt(cbPlats.getSelectedIndex());
        String fraga = "SELECT * FROM alien WHERE plats = (SELECT plats_ID FROM plats where benamning ='" + benamning + "');";
        sokAllAliendata(fraga);
    }//GEN-LAST:event_btnSokOmradeActionPerformed

    private void cbPlatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlatsActionPerformed


    }//GEN-LAST:event_cbPlatsActionPerformed

    // tar fram alla Aliens som regsiterats under vald period.
    private void btbSokDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbSokDatumActionPerformed
        txtArea.setText("");
        String franDatum = txtFaltFranDatum.getText();
        String tillDatum = txtFaltTillDatum.getText();
        String fraga = "SELECT * FROM alien WHERE Registreringsdatum BETWEEN '" + franDatum + "' AND '" + tillDatum + "';";
        sokAllAliendata(fraga);

    }//GEN-LAST:event_btbSokDatumActionPerformed

    
    // tar fram alla Aliens som har en viss ras
    private void btnSokRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokRasActionPerformed
        txtArea.setText("");
        String ras = cbRas.getItemAt(cbRas.getSelectedIndex());
        String fraga = "SELECT * FROM alien WHERE Alien_ID IN (SELECT Alien_ID FROM " + ras + ");";
        sokAllAliendata(fraga);
    }//GEN-LAST:event_btnSokRasActionPerformed

    private void cbRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRasActionPerformed

    private void txtFaltNamnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFaltNamnFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaltNamnFocusGained

    private void txtFaltTillDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaltTillDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaltTillDatumActionPerformed

    // fyller i combobox för plats
    public void fyllicbPlats() {

        try {
            String fraga = "SELECT benamning from plats;";

            ArrayList<String> allaOmraden;

            allaOmraden = idb.fetchColumn(fraga);

            for (String namn : allaOmraden) {
                cbPlats.addItem(namn);
                System.out.println(namn);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        } catch (Exception ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        }
    }

    // fyller i combobox för ras
    public void fyllicbRas() {
        cbRas.addItem("Boglodite");
        cbRas.addItem("Squid");
        cbRas.addItem("Worm");

    }

    // huvudfrågan som amvänds vid alla sökningar
    public void sokAllAliendata(String fraga) {
        try {
            ArrayList<HashMap<String, String>> alienInfo = idb.fetchRows(fraga);
            txtArea.append("Alien_ID" + "\t" + "Namn" + "\t"
                    + "Losenord" + "\t" + "Telefon" + "\t" + "Plats" + "\t" + "Ansvarig Agent" + "\t" + "Reg-datum" + "\n");
            for (HashMap<String, String> rad : alienInfo) {
                txtArea.append(rad.get("Alien_ID") + "\t");
                txtArea.append(rad.get("Namn") + "\t");
                txtArea.append(rad.get("Losenord") + "\t");
                txtArea.append(rad.get("Telefon") + "\t");
                txtArea.append(rad.get("Plats") + "\t");
                txtArea.append(rad.get("Ansvarig_Agent") + "\t");
                txtArea.append(rad.get("Registreringsdatum") + "\n");

            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        } catch (Exception ettUndantag) { //lägger även till nullpointer exception
            JOptionPane.showMessageDialog(null, "Ett fel uppstod!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbSokDatum;
    private javax.swing.JButton btnSokNamn;
    private javax.swing.JButton btnSokOmrade;
    private javax.swing.JButton btnSokRas;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbPlats;
    private javax.swing.JComboBox<String> cbRas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFranDatum;
    private javax.swing.JLabel lblSokNamn;
    private javax.swing.JLabel lblSokOmrade;
    private javax.swing.JLabel lblSokRas;
    private javax.swing.JLabel lblTillDatum;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtFaltFranDatum;
    private javax.swing.JTextField txtFaltNamn;
    private javax.swing.JTextField txtFaltTillDatum;
    // End of variables declaration//GEN-END:variables
}
