
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erik
 */
public class ÄndraLösenordAgent extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form ÄndraLösenordAgent
     */
    public ÄndraLösenordAgent(InfDB idb) {
        initComponents();
        this.idb = idb;
        agentID = InloggadAgent.getID();
        admin = false;
    }
    public ÄndraLösenordAgent(InfDB idb, boolean b) {
        initComponents();
        this.idb = idb;
        agentID = InloggadAdmin.getID();
        admin = true; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        lblGammalt = new javax.swing.JLabel();
        lblNytt = new javax.swing.JLabel();
        lblBekrafta = new javax.swing.JLabel();
        pfGammalt = new javax.swing.JPasswordField();
        pfNytt = new javax.swing.JPasswordField();
        pfBekrafta = new javax.swing.JPasswordField();
        btnAndra = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRubrik.setText("Ändra lösenord");

        lblGammalt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGammalt.setForeground(new java.awt.Color(51, 51, 51));
        lblGammalt.setText("Gammalt lösenord");

        lblNytt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNytt.setForeground(new java.awt.Color(51, 51, 51));
        lblNytt.setText("Nytt lösenord");

        lblBekrafta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBekrafta.setForeground(new java.awt.Color(51, 51, 51));
        lblBekrafta.setText("Bekräfta Lösenord");

        pfGammalt.setColumns(6);

        pfNytt.setColumns(6);
        pfNytt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfNyttActionPerformed(evt);
            }
        });

        pfBekrafta.setColumns(6);
        pfBekrafta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfBekraftaActionPerformed(evt);
            }
        });

        btnAndra.setBackground(new java.awt.Color(51, 51, 51));
        btnAndra.setForeground(new java.awt.Color(255, 255, 255));
        btnAndra.setText("Ändra");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        btnTillbaka.setBackground(new java.awt.Color(51, 51, 51));
        btnTillbaka.setForeground(new java.awt.Color(255, 255, 255));
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MiBlogga3.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTillbaka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 187, Short.MAX_VALUE)
                        .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGammalt)
                            .addComponent(lblNytt)
                            .addComponent(lblBekrafta))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfBekrafta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pfNytt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pfGammalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTillbaka)
                        .addGap(50, 50, 50)
                        .addComponent(lblRubrik)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGammalt)
                    .addComponent(pfGammalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNytt)
                    .addComponent(pfNytt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBekrafta)
                    .addComponent(pfBekrafta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfNyttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfNyttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfNyttActionPerformed

    private void pfBekraftaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfBekraftaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfBekraftaActionPerformed

    // ändrar lösenord ifall gamla löseordet stämmer och dom nya matchar varandra.
    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
       System.out.println(InloggadAgent.getID());
       if(Validering.textFaltHarVarde(pfGammalt) && Validering.textFaltHarVarde(pfNytt) && Validering.textFaltHarVarde(pfBekrafta)){
       if(Validering.isPasswordValid(pfGammalt) && Validering.isPasswordValid(pfNytt) && Validering.isPasswordValid(pfBekrafta)){
        try{
            String gammaltLosen = String.valueOf(pfGammalt.getPassword());
            String nyttLosen = String.valueOf(pfNytt.getPassword());
            String bekraftaLosen = String.valueOf(pfBekrafta.getPassword());
            String fraga = "SELECT Losenord FROM agent WHERE Agent_ID ='" + agentID + "'";
            String andra = "UPDATE agent SET Losenord = '" + nyttLosen +  "' WHERE Agent_ID = '" + agentID + "'";
            System.out.println(fraga + "    " + andra);
            if(idb.fetchSingle(fraga).equals(gammaltLosen) && nyttLosen.equals(bekraftaLosen)){
                idb.update(andra);
                JOptionPane.showMessageDialog(null, "Lösenordet har ändrats!");    
            }else{
                JOptionPane.showMessageDialog(null, "De nya lösenorden matchar inte.");
                pfNytt.requestFocus();
            }
        }
        catch (InfException ex) {
            Logger.getLogger(InloggadAgent.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"nånting gick fel");
        }
       }
       }
    }//GEN-LAST:event_btnAndraActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        dispose();
        if (admin) {
            new InloggadAdmin(idb).setVisible(true);
        } else {
            new InloggadAgent(idb).setVisible(true);
        }
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private boolean admin;
    private String agentID;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBekrafta;
    private javax.swing.JLabel lblGammalt;
    private javax.swing.JLabel lblNytt;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JPasswordField pfBekrafta;
    private javax.swing.JPasswordField pfGammalt;
    private javax.swing.JPasswordField pfNytt;
    // End of variables declaration//GEN-END:variables
}
