
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Erik
 */
public class ÄndraAlienInformation extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Creates new form AdminÄndraAlienInformation
     */
    public ÄndraAlienInformation(InfDB idb) {
        initComponents();
        this.idb = idb;
        fylliCBalienID();
        admin = false;
    }
        public ÄndraAlienInformation(InfDB idb, boolean b) {
        initComponents();
        this.idb = idb;
        fylliCBalienID();
        admin = true;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnAndra = new javax.swing.JButton();
        lblRubrik = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        btnTabort = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblExtra = new javax.swing.JLabel();
        txtFaltExtra = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lvlLosenord = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblAgent = new javax.swing.JLabel();
        lblPlats = new javax.swing.JLabel();
        lblValjRas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbAlienID = new javax.swing.JComboBox<>();
        txtFaltNamn = new javax.swing.JTextField();
        txtFaltLosen = new javax.swing.JPasswordField();
        txtFaltTelefon = new javax.swing.JTextField();
        cbAgent = new javax.swing.JComboBox<>();
        cbPlats = new javax.swing.JComboBox<>();
        cbRas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MiBlogga3.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        btnAndra.setBackground(new java.awt.Color(51, 51, 51));
        btnAndra.setForeground(new java.awt.Color(255, 255, 255));
        btnAndra.setText("Ändra");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        lblRubrik.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRubrik.setText("Ändra alien information");

        btnTillbaka.setBackground(new java.awt.Color(51, 51, 51));
        btnTillbaka.setForeground(new java.awt.Color(255, 255, 255));
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnTabort.setBackground(new java.awt.Color(51, 51, 51));
        btnTabort.setForeground(new java.awt.Color(255, 255, 255));
        btnTabort.setText("Ta bort");
        btnTabort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabortActionPerformed(evt);
            }
        });

        lblExtra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtFaltExtra.setColumns(5);
        txtFaltExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaltExtraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExtra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtFaltExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFaltExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Alien ID");

        lblNamn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNamn.setText("Namn:");

        lvlLosenord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lvlLosenord.setText("Lösenord:");

        lblTelefon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefon.setText("Telefon:");

        lblAgent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAgent.setText("Ansvarig Agent:");

        lblPlats.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPlats.setText("Välj område:");

        lblValjRas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValjRas.setText("Välj ras:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblNamn)
                    .addComponent(lvlLosenord)
                    .addComponent(lblTelefon)
                    .addComponent(lblAgent)
                    .addComponent(lblPlats)
                    .addComponent(lblValjRas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNamn)
                .addGap(18, 18, 18)
                .addComponent(lvlLosenord)
                .addGap(18, 18, 18)
                .addComponent(lblTelefon)
                .addGap(18, 18, 18)
                .addComponent(lblAgent)
                .addGap(18, 18, 18)
                .addComponent(lblPlats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblValjRas))
        );

        cbAlienID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlienIDActionPerformed(evt);
            }
        });

        txtFaltNamn.setColumns(7);

        txtFaltLosen.setColumns(7);

        txtFaltTelefon.setColumns(7);
        txtFaltTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaltTelefonActionPerformed(evt);
            }
        });

        cbAgent.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                cbAgentCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        cbAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgentActionPerformed(evt);
            }
        });

        cbPlats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlatsActionPerformed(evt);
            }
        });

        cbRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbAlienID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtFaltTelefon)
            .addComponent(cbAgent, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cbPlats, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFaltNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFaltLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cbAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFaltNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFaltLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFaltTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(btnAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnTabort, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(329, 329, 329))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(867, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnTillbaka)
                    .addGap(782, 782, 782)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTabort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel2))
                        .addComponent(btnTillbaka))
                    .addContainerGap(322, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFaltTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaltTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaltTelefonActionPerformed

    private void cbAgentCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cbAgentCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAgentCaretPositionChanged

    private void cbAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgentActionPerformed

    }//GEN-LAST:event_cbAgentActionPerformed

    private void cbPlatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPlatsActionPerformed

     // Hämtar text som är inskriven i comboboxar och textfält och uppdaterar en Alien i databasen.
    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
        if(Validering.isPasswordValid(txtFaltLosen) && Validering.textFaltHarVarde(txtFaltNamn) && Validering.isHeltal(txtFaltTelefon)){
        try {
            String valtLosen = String.valueOf(txtFaltLosen.getPassword());
            String valtNamn = txtFaltNamn.getText();
            String valdTelefon = txtFaltTelefon.getText();
            String valdAnsvarigAgent = cbAgent.getItemAt(cbAgent.getSelectedIndex());
            String valdPlats = cbPlats.getItemAt(cbPlats.getSelectedIndex());
            String fragaplats = "SELECT Plats_ID FROM plats WHERE Benamning = '" + valdPlats + "';";
            String valdPlatsID = idb.fetchSingle(fragaplats);
            String andra = "UPDATE alien SET Losenord = '" + valtLosen + "', Namn = '" + valtNamn + "', Telefon = '" + valdTelefon + "', Ansvarig_agent = "
                    + valdAnsvarigAgent + ", Plats = " + valdPlatsID + " WHERE Alien_ID = " + cbAlienID.getItemAt(cbAlienID.getSelectedIndex()) + ";";
            idb.update(andra);
            JOptionPane.showMessageDialog(rootPane, txtFaltNamn.getText() + " har uppdaterats i registret!");
        } catch (Exception ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());

        }
        }
    }//GEN-LAST:event_btnAndraActionPerformed

    // // Denna autofyller alla boxar och textfält, vid ett val av Alien-id.
    private void cbAlienIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlienIDActionPerformed
        try {
            if (cbAgent.getItemCount() == 0 && cbPlats.getItemCount() == 0 && cbRas.getItemCount() == 0) {
                fylliCBagentID();
                fylliCbPlats();
                fyllicbRas();
            }
            String alien = cbAlienID.getItemAt(cbAlienID.getSelectedIndex());
            String fraga = "SELECT * FROM alien WHERE Alien_ID = " + alien + ";";
            String fraga2 = "SELECT agent_ID FROM agent;";
            String fraga3 = "SELECT Ansvarig_agent FROM alien WHERE Alien_ID = " + alien + ";";
            String fraga4 = "SELECT benamning FROM plats WHERE Plats_ID = (SELECT Plats FROM alien WHERE Alien_ID = " + alien + ");";
            // Frågor för hämtning av aliens i respektive ras.
            String fraga5 = "SELECT Alien_ID FROM boglodite;";
            String fraga6 = "SELECT Alien_ID FROM squid;";
            String fraga7 = "SELECT Alien_ID FROM worm;";
            String alienRas = "Okänd ras";
            ArrayList<String> allaAgenter = idb.fetchColumn(fraga2);
            //Skapa arrayList för varje ras
            ArrayList<String> bogloditeArrayList = idb.fetchColumn(fraga5);
            ArrayList<String> squidArrayList = idb.fetchColumn(fraga6);
            ArrayList<String> wormArrayList = idb.fetchColumn(fraga7);
            //Anger värde på rasvariabel (måste hårdkodas)
            if (bogloditeArrayList.contains(alien)) {
                alienRas = "Boglodite";
            } else if (squidArrayList.contains(alien)) {
                alienRas = "Squid";
            } else if (wormArrayList.contains(alien)) {
                alienRas = "Worm";
            }

            boolean rasFound = false;
            boolean agentFound = false;
            boolean platsFound = false;
            int rasPosition = 0;
            int agentPosition = 0;
            int platsPosition = 0;
            for (int i = 0; !agentFound && i < allaAgenter.size(); i++) {
                String agent = allaAgenter.get(i);
                if (agent.equals(idb.fetchSingle(fraga3))) {
                    agentFound = true;
                } else {
                    agentPosition++;
                }
            }
            for (int i = 0; !platsFound && i < cbPlats.getItemCount(); i++) {
                String benamning = cbPlats.getItemAt(i);
                if (benamning.equals(idb.fetchSingle(fraga4))) {
                    platsFound = true;
                } else {
                    platsPosition++;
                }
            }
            for (int i = 0; !rasFound && i < cbRas.getItemCount(); i++) {
                String ras = cbRas.getItemAt(i);
                if (ras.equals(alienRas)) {
                    rasFound = true;
                } else {
                    rasPosition++;
                }
            }
            ArrayList<HashMap<String, String>> alienInfo = idb.fetchRows(fraga);
            for (HashMap<String, String> rad : alienInfo) {
                txtFaltNamn.setText(rad.get("Namn"));
                txtFaltLosen.setText(rad.get("Losenord"));
                cbAgent.setSelectedIndex(agentPosition);
                txtFaltTelefon.setText(rad.get("Telefon"));
                cbPlats.setSelectedIndex(platsPosition);
                cbRas.setSelectedIndex(rasPosition);
                fylliExtra();
                //Agent.add
                //bPlats.setSelectedIndex(position);
            }
            fylliExtra();
        } catch (Exception ettUndantag) { //lägger även till nullpointer exception
            JOptionPane.showMessageDialog(null, "Ett fel uppstod!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());

        }
    }//GEN-LAST:event_cbAlienIDActionPerformed

    //avslutar en pågående sida och öppnar en föregående.
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        dispose();
        if(admin){
            new InloggadAdmin(idb).setVisible(true);
        }
        else if (!admin) {
            new InloggadAgent(idb).setVisible(true);
        }
    }//GEN-LAST:event_btnTillbakaActionPerformed

    // tar bort en alien från databasen.
    private void btnTabortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabortActionPerformed
        try {
            String fraga = "DELETE FROM alien WHERE alien_ID = '" + cbAlienID.getItemAt(cbAlienID.getSelectedIndex()) + "';";

            idb.delete(fraga);
            JOptionPane.showMessageDialog(rootPane, "Alien har tagits bort ur registret!");
            dispose();
            new ÄndraAlienInformation(idb).setVisible(true);

        } catch (Exception ettUndantag) { //lägger även till nullpointer exception
            JOptionPane.showMessageDialog(null, "Ett fel uppstod!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());

        }
    }//GEN-LAST:event_btnTabortActionPerformed

    private void cbRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRasActionPerformed
    fylliExtra();
    }//GEN-LAST:event_cbRasActionPerformed

    private void fylliExtra(){
        String ras = cbRas.getItemAt(cbRas.getSelectedIndex());
        String extra = cbAlienID.getItemAt(cbAlienID.getSelectedIndex());
        String fragaBoogies = "SELECT Antal_Boogies FROM boglodite WHERE Alien_ID = " + extra + ";";
        String fragaArmar = "SELECT Antal_Armar FROM squid WHERE Alien_ID = " + extra + ";";
        try{
            String svarBoogies = idb.fetchSingle(fragaBoogies);
            String svarArmar = idb.fetchSingle(fragaArmar);
        
        if (ras.equals("Boglodite")) {
            lblExtra.setVisible(true);
            lblExtra.setText("Antal Boogies");
            txtFaltExtra.setVisible(true);
            txtFaltExtra.setText(svarBoogies);
        }
        if (ras.equals("Squid")) {
            lblExtra.setVisible(true);
            lblExtra.setText("Antal Armar");
            txtFaltExtra.setVisible(true);
            txtFaltExtra.setText("");
            txtFaltExtra.setText(svarArmar);
        }
        if (ras.equals("Worm")) {
            lblExtra.setVisible(false);
            txtFaltExtra.setVisible(false);
        }
        if (ras.equals("Okänd ras")) {
            lblExtra.setVisible(false);
            txtFaltExtra.setVisible(false);
        }
        }
    catch (Exception ettUndantag) { //lägger även till nullpointer exception
            JOptionPane.showMessageDialog(null, "Ett fel uppstod!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());

        }
    }    
    
    
    private void txtFaltExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaltExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaltExtraActionPerformed
    
    public void fyllicbRas() {
        cbRas.addItem("Boglodite");
        cbRas.addItem("Squid");
        cbRas.addItem("Worm");
        cbRas.addItem("Okänd ras");

    }

    // fyller i comboboxen för alien-id
    private void fylliCBalienID() {
        try {
            String fraga = "SELECT Alien_ID from alien ORDER BY Alien_ID ASC;";

            ArrayList<String> allaAlien;

            allaAlien = idb.fetchColumn(fraga);

            for (String namn : allaAlien) {
                cbAlienID.addItem(namn);
            }

        } catch (Exception ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        }
    }

     // fyller i comboboxen för agent-id
    private void fylliCBagentID() {
        try {
            String fraga = "SELECT Agent_ID from agent ORDER BY Agent_ID ASC;";

            ArrayList<String> allaAgenter;

            allaAgenter = idb.fetchColumn(fraga);

            for (String namn : allaAgenter) {
                cbAgent.addItem(namn);
            }

        } catch (Exception ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        }
    }

    // fyller i comboboxen för plats
    public void fylliCbPlats() {
        String fraga = "SELECT benamning from plats";

        ArrayList<String> allaOmraden;

        try {

            allaOmraden = idb.fetchColumn(fraga);

            for (String namn : allaOmraden) {
                cbPlats.addItem(namn);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        } catch (Exception ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        }
    }


    private boolean admin;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnTabort;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbAgent;
    private javax.swing.JComboBox<String> cbAlienID;
    private javax.swing.JComboBox<String> cbPlats;
    private javax.swing.JComboBox<String> cbRas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAgent;
    private javax.swing.JLabel lblExtra;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblPlats;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblValjRas;
    private javax.swing.JLabel lvlLosenord;
    private javax.swing.JTextField txtFaltExtra;
    private javax.swing.JPasswordField txtFaltLosen;
    private javax.swing.JTextField txtFaltNamn;
    private javax.swing.JTextField txtFaltTelefon;
    // End of variables declaration//GEN-END:variables
}
